name: Reviewdog LanguageTool
on: [pull_request]
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-languagetool@v1.20.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          language: 'en-US'
          patterns: '**/*.md **/*.MD **/*.txt'
          disabled_categories: ''
          disabled_rules: ''
      - uses: reviewdog/action-misspell@v1.26.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: error
          locale: "US"
          pattern: *.md
