name: Reviewdog LanguageTool
on: [pull_request]
jobs:
  reviewdog:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: reviewdog/action-languagetool@v1.20.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          patterns: '**/*.md **/*.MD **/*.txt'
          disabled_categories: ''
          disabled_rules: 'WHITESPACE_RULE,EN_QUOTES,DASH_RULE,WORD_CONTAINS_UNDERSCORE,UPPERCASE_SENTENCE_START,ARROWS,COMMA_PARENTHESIS_WHITESPACE,UNLIKELY_OPENING_PUNCTUATION,SENTENCE_WHITESPACE,CURRENCY,EN_UNPAIRED_BRACKETS,PHRASE_REPETITION,PUNCTUATION_PARAGRAPH_END,METRIC_UNITS_EN_US,ENGLISH_WORD_REPEAT_BEGINNING_RULE'
      - uses: reviewdog/action-misspell@v1.26.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
